### ISSUE TITLE
Running model in Int8 on a single GPU (24GB)

### ISSUE THREAD

**Issue by SOCSChamp** [facebookresearch/llama-recipes#171] opened 2023-03-04 19:31 UTC
Hi all,

This isn't my work, but the initial promise of this model for many people was that it could potentially be run on consumer hardware.

https://github.com/tloen/llama-int8.git

I found this implementation with bitsandbytes 8bit, brining resource requirements for 13B down to something a 3090 or 4090 could run.  Is there any work being done on making this whole thing compatible with HF Transformers, PEFT, LoRAs, etc?  Also, is there general interest in submitting PRs for these to be merged into this repo?

I'd be happy to contribute if there is.

**Comment by jspisak** [comment] 2023-09-06 18:47
Transferring this to the llama-recipes repo. thanks!

**Comment by HamidShojanazeri** [comment] 2023-12-13 21:21
closing as the issue is stale and can be addressed using HF checkpoints and inference [example](https://github.com/facebookresearch/llama-recipes/blob/main/examples/inference.py).

**Closed by HamidShojanazeri** 2023-12-13 21:21 UTC
